export type BedrockResponse = {
    id?: string; // Optional lesson ID generated by backend or Claude
    lessonTitle?: string;
    source?: string;
    estimatedDuration?: string;
    objectives?: string[];
    modules: Array<{
      id?: string;
      type: "text" | "code" | "quiz" | string;
      content: string;
      quizOptions?: string[];
      correctAnswer?: string;
    }>;
  };
  